apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==   # base64("root")
  SPRING_DATASOURCE_PASSWORD: cm9vdA==   # base64("root")
